# Generated by Django 4.1.1 on 2022-09-25 18:34

from django.db import migrations

def create_groups(apps, schema_editor):
    """
    This method is created to add groups.
    """
    group_names = ["Admin", "Student"]
    group_model = apps.get_model("auth", "Group")
    for name in group_names:
        group = group_model()
        group.name = name
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_groups)]
